# Generated by Django 4.1.5 on 2023-05-14 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_rename_id_wos_publications_id_crossref'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=150, verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nachname')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Benutzername')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email-Adresse')),
                (
                    'user',
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
