# Generated by Django 4.2.1 on 2023-05-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_publications_id_crossref'),
        ('app', '0005_userstats_profileuser'),
    ]

    operations = []
