# Generated by Django 4.1.5 on 2023-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20230515_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='id_crossref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
